name: Deploy Backend

on:
  push:
    branches: [ "deployBack" ]
  pull_request:
    branches: [ "deployBack" ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo pip install gigalixir --ignore-installed six
      - run: gigalixir login -e "rickdep1999@gmail.com" -y -p "richard99"
      - run: gigalixir git:remote timemanager-epitech-mpl	
      - run: git push gigalixir
    
