# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run Deploy Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  all:
    name: Run Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create subtree
        run: git subtree push --prefix timemanager origin deployBack
      - name: Checkout subtree
        run: git checkout deployBack
      - name: install gigalixir
        run: sudo pip install gigalixir --ignore-installed six
      - name: Login gigalixir
        run: gigalixir login -e "rickdep1999@gmail.com" -y -p "richard99"
      - name: Add gigalixir git to project
        run: gigalixir git:remote timemanager-epitech-mpl	
      - name: Push to gigalixir
        run: git push -f gigalixir HEAD:refs/heads/main
      - name: Git checkout main
        run: git checkout main
      - name: Delete subtree
        run: git push origin --delete deployBack
