name: Deploy Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v1
      - run: sudo pip install gigalixir --ignore-installed six
      - run: gigalixir login -e "rickdep1999%40gmail.com" -y -p "richard99"
      - run: gigalixir git:remote timemanager-epitech-mpl	
      - run: git push -f gigalixir HEAD:refs/heads/main
    
