# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  all:
    name: Run docker compose
    runs-on: ubuntu-latest
    steps:
      - name: Docker compose up
        run: docker-compose up --build
      - run: echo "🍏 This job's status is ${{ job.status }}."
